# Generated by Django 5.2.13 on 2026-04-28 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=220, unique=True)),
                ('one_sentence_summary', models.CharField(max_length=255)),
                ('business_problem', models.TextField()),
                ('tools_used', models.TextField(blank=True)),
                ('key_features', models.TextField(blank=True)),
                ('role_contribution', models.TextField(blank=True)),
                ('biggest_challenge', models.TextField(blank=True)),
                ('what_i_learned', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='projects/')),
                ('github_url', models.URLField(blank=True)),
                ('demo_url', models.URLField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['title'],
            },
        ),
    ]
