# Generated by Django 5.2.13 on 2026-04-30 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='demo_url',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
