# Generated by Django 5.2.13 on 2026-04-30 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_project_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='prompt_text',
            field=models.TextField(blank=True),
        ),
    ]
