# Generated by Django 5.2.13 on 2026-05-05 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_project_prompt_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='workflow_image',
            field=models.ImageField(blank=True, null=True, upload_to='projects/workflows/'),
        ),
    ]
