# Generated by Django 5.2.13 on 2026-05-12 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_project_workflow_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='email_output',
            field=models.TextField(blank=True),
        ),
    ]
