# Generated by Django 5.2.13 on 2026-05-03 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='About', max_length=120)),
                ('intro', models.TextField(blank=True)),
                ('story_title', models.CharField(default='My Story', max_length=120)),
                ('story_text', models.TextField(blank=True)),
                ('bring_title', models.CharField(default='What I Bring', max_length=120)),
                ('bring_points', models.TextField(blank=True, help_text='One bullet per line.')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='SkillsPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Skills', max_length=120)),
                ('intro', models.TextField(blank=True)),
                ('skills_text', models.TextField(blank=True, help_text='One skill per line.')),
                ('tip_title', models.CharField(default='Tip', max_length=120)),
                ('tip_text', models.TextField(blank=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['title'],
            },
        ),
    ]
