# Generated by Django 6.0.4 on 2026-04-16 21:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('academics', 'Academics'), ('creative', 'Creative'), ('tech', 'Tech'), ('wellness', 'Wellness'), ('other', 'Other')], max_length=25)),
                ('is_free', models.BooleanField(default=False)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('contact_preference', models.CharField(choices=[('email', 'Email'), ('phone', 'Phone'), ('chat', 'Chat')], max_length=20)),
                ('availability_status', models.CharField(choices=[('available', 'Available'), ('busy', 'Busy'), ('scheduled', 'Scheduled')], default='available', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
