# Generated by Django 6.0.4 on 2026-04-21 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0003_alter_bookingrequest_options_alter_review_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skill',
            name='category',
            field=models.CharField(choices=[('academics', 'Academics'), ('tech', 'Tech'), ('creative', 'Creative'), ('wellness', 'Wellness'), ('other', 'Other')], max_length=50),
        ),
    ]
