# Generated by Django 5.2.13 on 2026-04-22 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0005_remove_bookingrequest_preferred_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skill',
            name='contact_preference',
            field=models.CharField(choices=[('email', 'Email'), ('phone', 'Phone')], max_length=20),
        ),
    ]
